let startBtn= document.getElementById('start');
let homeBtn= document.getElementById('home');
let restartBtn=document.getElementById('restart');
let game=document.getElementById('game');
let start=document.getElementById('start');
let restart=document.getElementById('restart');
let home=document.getElementById('home');
let btns=document.getElementById('buttonsLocation');
let title=document.getElementById('title');
let rule=document.getElementById('rule');
function startGame() {
      game.src=game.src;
      game.style.display="initial";
      restart.style.display="initial";
      home.style.display="initial";
      start.style.display="none";
      btns.style.justifyContent="space-between";
      title.style.fontSize="36px";
      rule.style.display="none";
      // let game = document.createElement('iframe');
      // // game.style.display = 'none';
      // game.src = "https://darrin-lin.github.io/space-game-test/";
      // game.height = "585px";
      // game.width = "960px";
      // document.getElementById('gameLocation').appendChild(game);
      // let re = document.createElement('button');
      // re.id='restart';
      // re.textContent="RESTART";
      // document.getElementById('buttonsLocation').appendChild(re);
      // let hm = document.createElement('button');
      // hm.id='home';
      // hm.textContent="HOME";
      // document.getElementById('buttonsLocation').appendChild(hm);
      // const rmst = document.getElementById('start');
      // rmst.remove();
      // homeBtn= document.getElementById('home');
};
function startPage() {
      title.style.fontSize="60px";
      game.style.display="none";
      restart.style.display="none";
      home.style.display="none";
      btns.style.justifyContent="space-around";
      start.style.display="initial";
      rule.style.display="initial";
      // let sta = document.createElement('button');
      // sta.id='start';
      // sta.textContent="START";
      // document.getElementById('buttonsLocation').appendChild(sta);
      // const rmre = document.getElementById('restart');
      // rmre.remove();
      // const rmhm = document.getElementById('home');
      // rmhm.remove();
      // startBtn= document.getElementById('start');
};
function restartGame(){
      game.src=game.src;
};
window.addEventListener('load',startPage);
startBtn.addEventListener('click',startGame);
homeBtn.addEventListener('click',startPage);
restartBtn.addEventListener('click',restartGame);